import "../styles/globals.css";
import styles from '../styles/layout.module.css';
export const metadata = {
  title: 'bdtest',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.bannerHeader}>
          <nav>
            <ul>
              <li><h2 className={styles.h2}>bdtest_</h2></li>
            </ul>
          </nav>
        </header>
        <div className={styles.preRoot}>           
        {children}
        </div>
        <footer className={styles.footer}>
          <p>BDT COSAS</p>
        </footer>
      </body>
    </html>
  )
}
